# Generated by Django 4.1.5 on 2023-01-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('mbaNo', models.TextField()),
                ('coFileNo', models.TextField()),
                ('ded', models.TextField()),
                ('dld', models.TextField()),
                ('manager', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
