# Generated by Django 4.1.5 on 2023-01-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_apfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='apfo',
            field=models.DateField(null=True),
        ),
    ]
