# Generated by Django 4.1.5 on 2023-01-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fName',
        ),
        migrations.AddField(
            model_name='contact',
            name='lName',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
