# Generated by Django 4.1.5 on 2023-01-09 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_apfo'),
        ('api', '0003_rename_name_contact_fname_contact_lname'),
    ]

    operations = [
    ]
