# Generated by Django 4.1.5 on 2023-01-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20230109_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.TextField(default='Active'),
            preserve_default=False,
        ),
    ]
