# Generated by Django 4.1.5 on 2023-01-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('body', models.TextField(max_length=255, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
