# Generated by Django 4.1.5 on 2023-01-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_announcement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True, default='2018-11-20T15:58:44.767594-06:00'),
            preserve_default=False,
        ),
    ]
