# Generated by Django 4.1.5 on 2023-01-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_announcement_date_announcement_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='dateTime',
        ),
    ]
