# Generated by Django 4.1.5 on 2023-01-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_announcement_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='dateTime',
            new_name='date',
        ),
    ]
