# Generated by Django 4.1.5 on 2023-01-29 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_link'),
        ('api', '0011_rename_datetime_announcement_date'),
    ]

    operations = [
    ]
